Collections:
- Metadata:
    Architecture:
    - MobilenetV2
  Name: mobilenetv2_coco_wholebody_hand
  Paper:
  - http://openaccess.thecvf.com/content_cvpr_2018/html/Sandler_MobileNetV2_Inverted_Residuals_CVPR_2018_paper.html
  - https://link.springer.com/chapter/10.1007/978-3-030-58545-7_12
  README: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/coco_wholebody_hand/mobilenetv2_coco_wholebody_hand.md
Models:
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/coco_wholebody_hand/mobilenetv2_coco_wholebody_hand_256x256.py
  In Collection: mobilenetv2_coco_wholebody_hand
  Metadata:
    Training Data: COCO-WholeBody-Hand
  Name: hand--2d_kpt_sview_rgb_img--topdown_heatmap--coco_wholebody_hand--mobilenetv2_coco_wholebody_hand_256x256
  Results:
  - Dataset: COCO-WholeBody-Hand
    Metrics:
      AUC: 0.829
      EPE: 4.77
      PCK@0.2: 0.795
    Task: 2D Hand Pose Estimation
  Weights: https://download.openmmlab.com/mmpose/hand/mobilenetv2/mobilenetv2_coco_wholebody_hand_256x256-06b8c877_20210909.pth
