Collections:
- Metadata:
    Architecture:
    - SCNet
  Name: scnet_coco_wholebody_hand
  Paper:
  - http://openaccess.thecvf.com/content_CVPR_2020/html/Liu_Improving_Convolutional_Networks_With_Self-Calibrated_Convolutions_CVPR_2020_paper.html
  - https://link.springer.com/chapter/10.1007/978-3-030-58545-7_12
  README: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/coco_wholebody_hand/scnet_coco_wholebody_hand.md
Models:
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/coco_wholebody_hand/scnet50_coco_wholebody_hand_256x256.py
  In Collection: scnet_coco_wholebody_hand
  Metadata:
    Training Data: COCO-WholeBody-Hand
  Name: hand--2d_kpt_sview_rgb_img--topdown_heatmap--coco_wholebody_hand--scnet50_coco_wholebody_hand_256x256
  Results:
  - Dataset: COCO-WholeBody-Hand
    Metrics:
      AUC: 0.834
      EPE: 4.55
      PCK@0.2: 0.803
    Task: 2D Hand Pose Estimation
  Weights: https://download.openmmlab.com/mmpose/hand/scnet/scnet50_coco_wholebody_hand_256x256-e73414c7_20210909.pth
