Collections:
- Metadata:
    Architecture:
    - Hourglass
  Name: hourglass_coco_wholebody_face
  Paper:
  - https://link.springer.com/chapter/10.1007/978-3-319-46484-8_29
  - https://link.springer.com/chapter/10.1007/978-3-030-58545-7_12
  README: configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/coco_wholebody_face/hourglass_coco_wholebody_face.md
Models:
- Config: configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/coco_wholebody_face/hourglass52_coco_wholebody_face_256x256.py
  In Collection: hourglass_coco_wholebody_face
  Metadata:
    Training Data: COCO-WholeBody-Face
  Name: face--2d_kpt_sview_rgb_img--topdown_heatmap--coco_wholebody_face--hourglass52_coco_wholebody_face_256x256
  Results:
  - Dataset: COCO-WholeBody-Face
    Metrics:
      NME: 0.0586
    Task: 2D Face Landmark Detection
  Weights: https://download.openmmlab.com/mmpose/face/hourglass/hourglass52_coco_wholebody_face_256x256-6994cf2e_20210909.pth
