Collections:
- Metadata:
    Architecture:
    - SCNet
  Name: scnet_coco_wholebody_face
  Paper:
  - http://openaccess.thecvf.com/content_CVPR_2020/html/Liu_Improving_Convolutional_Networks_With_Self-Calibrated_Convolutions_CVPR_2020_paper.html
  - https://link.springer.com/chapter/10.1007/978-3-030-58545-7_12
  README: configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/coco_wholebody_face/scnet_coco_wholebody_face.md
Models:
- Config: configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/coco_wholebody_face/scnet50_coco_wholebody_face_256x256.py
  In Collection: scnet_coco_wholebody_face
  Metadata:
    Training Data: COCO-WholeBody-Face
  Name: face--2d_kpt_sview_rgb_img--topdown_heatmap--coco_wholebody_face--scnet50_coco_wholebody_face_256x256
  Results:
  - Dataset: COCO-WholeBody-Face
    Metrics:
      NME: 0.0565
    Task: 2D Face Landmark Detection
  Weights: https://download.openmmlab.com/mmpose/face/scnet/scnet50_coco_wholebody_face_256x256-a0183f5f_20210909.pth
