Collections:
  - Name: HRNet
    Metadata:
      Training Techniques:
        - Adam
      Architecture:
        - HRNet
    README: configs/top_down/hrnet/README.md
    Paper: https://arxiv.org/abs/1902.09212

Models:
  - Name: hrnet_w32_coco_256x192_fp16_dynamic
    In Collection: HRNet
    Config: configs/top_down/hrnet/coco/hrnet_w32_coco_256x192_fp16_dynamic.py
    Metadata:
      Training Data: COCO
      FLOPs: 7700000000
      Parameters: 28540000
    Results:
      - Task: 2D Human Pose Estimation
        Dataset: COCO
        Metrics:
          AP: 0.746
          AP50: 0.905
          AP75: 0.88
          AR: 0.800
          AR50: 0.943
    Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_256x192_fp16_dynamic-290efc2e_20210430.pth
    Paper:
      - https://arxiv.org/abs/1902.09212
      - https://arxiv.org/abs/1710.03740

  - Name: hrnet_w32_coco_256x192
    In Collection: HRNet
    Config: configs/top_down/hrnet/coco/hrnet_w32_coco_256x192.py
    Metadata:
      Training Data: COCO
      FLOPs: 7700000000
      Parameters: 28540000
    Results:
      - Task: 2D Human Pose Estimation
        Dataset: COCO
        Metrics:
          AP: 0.746
          AP50: 0.904
          AP75: 0.819
          AR: 0.799
          AR50: 0.942
    Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_256x192-c78dce93_20200708.pth

  - Name: hrnet_w32_coco_384x288
    In Collection: HRNet
    Config: configs/top_down/hrnet/coco/hrnet_w32_coco_384x288.py
    Metadata:
      Training Data: COCO
      FLOPs: 17330000000
      Parameters: 28540000
    Results:
      - Task: 2D Human Pose Estimation
        Dataset: COCO
        Metrics:
          AP: 0.760
          AP50: 0.906
          AP75: 0.829
          AR: 0.810
          AR50: 0.943
    Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_384x288-d9f0d786_20200708.pth

  - Name: hrnet_w48_coco_256x192
    In Collection: HRNet
    Config: configs/top_down/hrnet/coco/hrnet_w48_coco_256x192.py
    Metadata:
      Training Data: COCO
      FLOPs: 15770000000
      Parameters: 63600000
    Results:
      - Task: 2D Human Pose Estimation
        Dataset: COCO
        Metrics:
          AP: 0.756
          AP50: 0.907
          AP75: 0.825
          AR: 0.806
          AR50: 0.942
    Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_256x192-b9e0b3ab_20200708.pth

  - Name: hrnet_w48_coco_384x288
    In Collection: HRNet
    Config: configs/top_down/hrnet/coco/hrnet_w48_coco_384x288.py
    Metadata:
      Training Data: COCO
      FLOPs: 35480000000
      Parameters: 63600000
    Results:
      - Task: 2D Human Pose Estimation
        Dataset: COCO
        Metrics:
          AP: 0.767
          AP50: 0.910
          AP75: 0.831
          AR: 0.816
          AR50: 0.946
    Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_coco_384x288-314c8528_20200708.pth

  - Name: hrnet_w32_mpii_256x256
    In Collection: HRNet
    Config: configs/top_down/hrnet/mpii/hrnet_w32_mpii_256x256.py
    Metadata:
      Training Data: MPII
      FLOPs: 17330000000
      Parameters: 28540000
    Results:
      - Task: 2D Human Pose Estimation
        Dataset: MPII
        Metrics:
          Mean: 0.900
          Mean@0.1: 0.334
    Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_mpii_256x256-6c4f923f_20200812.pth

  - Name: hrnet_48_mpii_256x256
    In Collection: HRNet
    Config: configs/top_down/hrnet/mpii/hrnet_w48_mpii_256x256.py
    Metadata:
      Training Data: MPII
      FLOPs: 10270000000
      Parameters: 28540000
    Results:
      - Task: 2D Human Pose Estimation
        Dataset: MPII
        Metrics:
          Mean: 0.901
          Mean@0.1: 0.337
    Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w48_mpii_256x256-92cab7bd_20200812.pth
